channels:
  - conda-forge
  - defaults
  - pytorch

dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-image
  - ipywidgets
  - ipython
  - pytorch
  - torchvision
  - torchsummary
  - pip:
      - torch
      - torchsummary
